#file1 and file2 correspond to files similar to RhoAndVar.txt generated by FindCorrAndVar.cpp. Outputs to 4 files: 'AllValues.txt', containing rho, var, C, S and D for each pair, and 'UseableCValues.txt', 'UseableDValues.txt', 'UseableSValues.txt', containing only C, D and S respectively for each gene pair. file1 and file2 must be of equal length, and sorted in equal order


import math
from pathlib import Path


def print_progress(step_name, current=None, total=None):
    if current is None or total is None:
        print(f"[FindCSD] {step_name}")
        return

    percent_complete = (current / total) * 100
    print(f"[FindCSD] {step_name}: {current}/{total} ({percent_complete:.1f}%)")

ROOT_DIR = Path(__file__).resolve().parents[2]
WTO_DIR = ROOT_DIR / "results" / "wTO"
NETWORKS_DIR = ROOT_DIR / "results" / "networks"
NETWORKS_DIR.mkdir(parents=True, exist_ok=True)

file1 = WTO_DIR / 'wTO_rna_normal_edgelist_1_1.txt'
file2 = WTO_DIR / 'wTO_rna_cancer_edgelist_1_1.txt'

print_progress('Teller linjer i input-filene')
with open(file1) as count_f1:
    total_lines = sum(1 for _ in count_f1)

progress_interval = max(1, total_lines // 10)

print_progress('Aapner input- og output-filer')
f1 = open(file1)
f2 = open(file2)
allVals = open(NETWORKS_DIR / 'AllValues_rna_WTO_1.txt', 'w')
cFile = open(NETWORKS_DIR / 'UseableCValues_rna_WTO_1.txt', 'w')
dFile = open(NETWORKS_DIR / 'UseableDValues_rna_WTO_1.txt', 'w')
sFile = open(NETWORKS_DIR / 'UseableSValues_rna_WTO_1.txt', 'w')

print("Gene1\tGene2\tRho1\tRho2\tC\tS\tD", file=allVals) 

print_progress('Behandler genpar')

for line_number, line1 in enumerate(f1, start=1):
    line2 = f2.readline()
    splitLine1 = line1.rstrip().split('\t')
    splitLine2 = line2.rstrip().split('\t')
    geneA = splitLine1[0]
    geneB =  splitLine1[1]
    rho1 =  float(splitLine1[2])
    #var1 =  float(splitLine1[3])
    rho2 = float(splitLine2[2])
    #var2 = float(splitLine2[3])

    #comboSD = math.sqrt(var1 + var2)
    
    if (geneA != geneB):
        cVal = abs(rho1+rho2) #/comboSD
        dVal = (abs(rho1)+abs(rho2)-abs(rho1+rho2)) #/comboSD
        sVal = abs(abs(rho1)-abs(rho2)) #/comboSD
        allVals.write(f"{geneA}\t{geneB}\t{rho1}\t{rho2}\t{cVal}\t{sVal}\t{dVal}\n")

        if (math.isnan(cVal) == False):
            print(cVal, file=cFile)
            print(sVal, file=sFile)
            print(dVal, file=dFile)

    
    if (geneA == geneB):
        cVal = -2
        dVal = -2
        sVal = -2

    if line_number % progress_interval == 0 or line_number == total_lines:
        print_progress('Behandler genpar', line_number, total_lines)


f1.close()
f2.close()
allVals.close()
cFile.close()
sFile.close()
dFile.close()
print_progress('FindCSD ferdig')
